export const FETCH_USUARIOS_START = 'FETCH_USUARIOS_START';
export const FETCH_USUARIOS_SUCCESS = 'FETCH_USUARIOS_SUCCESS';
export const FETCH_USUARIOS_FAIL = 'FETCH_USUARIOS_FAIL';

export const FETCH_USUARIO_START = 'FETCH_USUARIO_START';
export const FETCH_USUARIO_SUCCESS = 'FETCH_USUARIO_SUCCESS';
export const FETCH_USUARIO_FAIL = 'FETCH_USUARIO_FAIL';